### ISSUE TITLE
Does not seem to work for screenreader users

### ISSUE THREAD

**Issue by edhowland** [PeterCamilleri/mini_readline#34]
Hello,

I am a blind Ruby programmer and use a creenreader like VoiceOver on the Mac to read text. I tryed 2 of your programs that use this gem: fOOrth and mysh. Neither one reports any characters to the screenreader output. The only output I get is ' '. The characters appear to be there if I use the screen navigation commands to read the current line. They just do not echo correctly. This does not happen whenever I user irb, pry or just my own code with 👍  $ ruby -r readline ... then Readline.readline('>> ').

Also, their seems to be some strange behaviour with Control-C and Control-D. The ctrl-c should clear the line and ctrl-d should exit the REPL. 
Readline raises Interrupt for ctrl-c and returns nil for ctrl-d. I check these in my code and follow the pry and irb conventions. 

I would like to use these projects so am I not using the configuration correctly? Or is it possible to use either mysh or fOOrth with readline instead?

Regards, Ed

**Comment by edhowland** [comment]
Hello,

I noticed the subject line says "Does seem to work for screenreader users", and should say "Does not seem to work for screen reader users". But I could not change the subject line. My bad.

Regards, Ed

**Comment by PeterCamilleri** [comment]
Fixed the subject line. You may be the first to try this gem under the MAC so I am not surprised to see some issues. I know that mini_readline reads the keyboard in a raw mode and that may be a factor. I need to understand how the screen reader gets its input to see how this can be corrected. In the meantime could you specify your environment? OS version, Ruby version, Screen reader so I can try and take a stab at this?

**Comment by edhowland** [comment]
Hello,

Yes, I was using this in a VM on my MacBook Air running MacOS Sieera. The VM manager is VirtualBox and the guest OS is Ubuntu 14.04. The Ruby version is 2.2.2.p95

(This is my workspace) I haven't tried it in any other environment. 

I should mention that I have tried many Ruby gems for readline functionality and find they seem to not work for VoiceOver (the screenreader on the Mac). There is usually some little thing that seems not to work. I've tried :tty-reader, highline and some others. The one : 'readline' builtin to at least irb, seems to work the best. I never had any sort of problems back when my sight was better and I did not a screenreader. 

I was also wondering about the control key usage. If even just Control-D to exit worked, I might be able to progress a little further, because I can alway turn the screenreader in to pure read mode instead of interactive.

Regards, Ed

**Comment by PeterCamilleri** [comment]
Alt-z is supposed to be end-of-input, but I have no MAC to test with just now. I hope to fix this situation eventually. Maybe give that a try?

**Comment by edhowland** [comment]
Ok, I also installed the 'mysh' gem directly on my Mac.
Ruby version: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin14]


Yes, Alt-Z works to exit. So thanks.

I remember some Control or Alt Z from my MS-DOS days. But in the Unix days, I always use Control-D.

**Comment by PeterCamilleri** [comment]
This issue is now part of the mini_term gem since it embraces the cross platform issue.
